# @package _global_

env:
  name: BreakoutNoFrameskip-v4
  demo: BreakoutNoFrameskip-v4_multi_60_filtered.pkl
  replay_mem: 200000
  initial_mem: 5000
  eps_steps: 1e6
  eps_window: 10
  learn_steps: 1e6
  eval_interval: 5000
  atari_terminal_on_life_loss: False
  atari_clip_reward: False

expert:
  demos: 60
  subsample_freq: 1

eval:
  policy: trained_policies/softq_implicit_BreakoutNoFrameskip-v4
  threshold:  # optional: e.g. 10 to only save episodes with score >= 10
  use_baselines: True  # use in-repo softq policy (no baselines_zoo)
  eps: 25
  expert_algorithm: a2c
  deterministic: True

method:
  loss: value_expert
  chi: True
  alpha: 0.1

agent:
  init_temp: 0.1
  critic_target_update_frequency: 100

train:
  batch: 64
  use_target: True
  soft_update: True
  updates_per_step: 1

q_net:
  _target_: agent.softq_models.AtariQNetwork
